In [1]:
import sys
import os
sys.path.append(os.path.abspath("../../../src"))

In [2]:
import pandas as pd
df = pd.read_csv("../../../data/creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
from utils.preprocess import create_features
df = create_features(df)
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V25,V26,V27,V28,Amount,Class,_log_amount,Hour_from_start_mod24,is_night_proxy,is_business_hours_proxy
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.128539,-0.189115,0.133558,-0.021053,149.62,0,5.014760,0,1,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,0.167170,0.125895,-0.008983,0.014724,2.69,0,1.305626,0,1,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,5.939276,0,1,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,0.647376,-0.221929,0.062723,0.061458,123.50,0,4.824306,0,1,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.206010,0.502292,0.219422,0.215153,69.99,0,4.262539,0,1,0

In [4]:
#Tách Feature và Label
X = df.drop(["Class", "Time"], axis=1).columns.to_list()
y = "Class"

In [5]:
from utils import *
X_train, y_train, X_val, y_val, X_test, y_test = split_data(df, X, y)

X_train: (181584, 33) y_train: (181584,)
X_val: (45396, 33) y_val: (45396,)
X_test: (56746, 33) y_test: (56746,)
Fraud rate in train: 0.001910961318177813
Fraud rate in test: 0.0013040566735981391

In [6]:
#Dùng Pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000, random_state=42, class_weight="balanced"))
])

pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [7]:
pipe.named_steps["model"].n_iter_

array([35], dtype=int32)

In [8]:
#Predict xác suất
y_val_prob = pipe.predict_proba(X_val)[:, 1]
y_test_prob = pipe.predict_proba(X_test)[:, 1]
print(y_val_prob)
print(y_test_prob)

[0.01317983 0.10692782 0.05534639 ... 0.00027914 0.02447189 0.03172686]
[0.020414   0.01766961 0.01418569 ... 0.02209851 0.0777073  0.14370899]

In [9]:
import numpy as np

y_test = np.array(y_test).reshape(-1)
y_test_prob = np.array(y_test_prob).reshape(-1)

print(y_test.shape, y_test_prob.shape)

(56746,) (56746,)

In [10]:
def fast_sweep(y_test, y_test_prob, FP=5.0, FN=200.0):
    idx = np.argsort(-y_test_prob)
    y_test_prob = y_test_prob[idx]
    y_test = y_test[idx]

    tp = np.cumsum(y_test == 1)
    fp = np.cumsum(y_test == 0)

    total_pos = np.sum(y_test == 1)
    total_neg = np.sum(y_test == 0)

    fn = total_pos - tp
    tn = total_neg - fp

    precision = tp / (tp + fp + 1e-9)
    recall = tp / (tp + fn + 1e-9)
    f1 = 2 * precision * recall / (precision + recall + 1e-9)

    cost = fp * FP + fn * FN

    df = pd.DataFrame({
        'threshold': y_test_prob,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'tp': tp,
        'tn': tn,
        'fp': fp,
        'fn': fn,
        'cost': cost
    })

    return df.drop_duplicates('threshold')

In [11]:
df_sweep = fast_sweep(y_test, y_test_prob)

df_zoom = df_sweep[(df_sweep['threshold'] >= 0.968) & (df_sweep['threshold'] <= 0.970)]
print(df_zoom)

     threshold  precision    recall        f1  tp     tn   fp  fn    cost
173   0.969935   0.350575  0.824324  0.491935  61  56559  113  13  3165.0
174   0.969543   0.348571  0.824324  0.489960  61  56558  114  13  3170.0
175   0.969542   0.346591  0.824324  0.488000  61  56557  115  13  3175.0
176   0.969133   0.344633  0.824324  0.486056  61  56556  116  13  3180.0
177   0.969047   0.348315  0.837838  0.492063  62  56556  116  12  2980.0
178   0.968505   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
179   0.968155   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
180   0.968043   0.342541  0.837838  0.486275  62  56553  119  12  2995.0

In [12]:
def sweep_zoom_2(y_test, y_test_prob, FP=5.0, FN=200.0):
    thresholds = np.linspace(0.968, 0.970, 2000)  # 👈 thêm ở đây
    
    rows = []
    for thr in thresholds:
        y_pred = (y_test_prob >= thr).astype(int)

        tn, fp, fn, tp = confusion_matrix(y_test, y_pred, labels=[0,1]).ravel()

        precision = precision_score(y_test, y_pred, zero_division=0)
        recall = recall_score(y_test, y_pred, zero_division=0)
        f1 = f1_score(y_test, y_pred, zero_division=0)

        cost = fp * FP + fn * FN

        rows.append({
            'threshold': thr,
            'precision': precision,
            'recall': recall,
            'f1': f1,
            'tp': tp,
            'tn': tn,
            'fp': fp,
            'fn': fn,
            'cost': cost
        })

    return pd.DataFrame(rows)

In [13]:
df_zoom_2 = sweep_zoom_2(y_test, y_test_prob)
print(df_zoom_2)

      threshold  precision    recall        f1  tp     tn   fp  fn    cost
0      0.968000   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
1      0.968001   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
2      0.968002   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
3      0.968003   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
4      0.968004   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
...         ...        ...       ...       ...  ..    ...  ...  ..     ...
1995   0.969996   0.352601  0.824324  0.493927  61  56560  112  13  3160.0
1996   0.969997   0.352601  0.824324  0.493927  61  56560  112  13  3160.0
1997   0.969998   0.352601  0.824324  0.493927  61  56560  112  13  3160.0
1998   0.969999   0.352601  0.824324  0.493927  61  56560  112  13  3160.0
1999   0.970000   0.352601  0.824324  0.493927  61  56560  112  13  3160.0

[2000 rows x 9 columns]

In [15]:
import pandas as pd

pd.set_option('display.max_rows', None)
print(df_zoom_2)

      threshold  precision    recall        f1  tp     tn   fp  fn    cost
0      0.968000   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
1      0.968001   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
2      0.968002   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
3      0.968003   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
4      0.968004   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
5      0.968005   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
6      0.968006   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
7      0.968007   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
8      0.968008   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
9      0.968009   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
10     0.968010   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
11     0.968011   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
12     0.968012   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
13     0.968013   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
14     0.968014   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
15     0.968015   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
16     0.968016   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
17     0.968017   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
18     0.968018   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
19     0.968019   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
20     0.968020   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
21     0.968021   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
22     0.968022   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
23     0.968023   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
24     0.968024   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
25     0.968025   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
26     0.968026   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
27     0.968027   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
28     0.968028   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
29     0.968029   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
30     0.968030   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
31     0.968031   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
32     0.968032   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
33     0.968033   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
34     0.968034   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
35     0.968035   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
36     0.968036   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
37     0.968037   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
38     0.968038   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
39     0.968039   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
40     0.968040   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
41     0.968041   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
42     0.968042   0.342541  0.837838  0.486275  62  56553  119  12  2995.0
43     0.968043   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
44     0.968044   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
45     0.968045   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
46     0.968046   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
47     0.968047   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
48     0.968048   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
49     0.968049   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
50     0.968050   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
51     0.968051   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
52     0.968052   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
53     0.968053   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
54     0.968054   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
55     0.968055   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
56     0.968056   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
57     0.968057   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
58     0.968058   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
59     0.968059   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
60     0.968060   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
61     0.968061   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
62     0.968062   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
63     0.968063   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
64     0.968064   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
65     0.968065   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
66     0.968066   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
67     0.968067   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
68     0.968068   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
69     0.968069   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
70     0.968070   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
71     0.968071   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
72     0.968072   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
73     0.968073   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
74     0.968074   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
75     0.968075   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
76     0.968076   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
77     0.968077   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
78     0.968078   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
79     0.968079   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
80     0.968080   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
81     0.968081   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
82     0.968082   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
83     0.968083   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
84     0.968084   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
85     0.968085   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
86     0.968086   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
87     0.968087   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
88     0.968088   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
89     0.968089   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
90     0.968090   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
91     0.968091   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
92     0.968092   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
93     0.968093   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
94     0.968094   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
95     0.968095   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
96     0.968096   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
97     0.968097   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
98     0.968098   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
99     0.968099   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
100    0.968100   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
101    0.968101   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
102    0.968102   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
103    0.968103   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
104    0.968104   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
105    0.968105   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
106    0.968106   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
107    0.968107   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
108    0.968108   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
109    0.968109   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
110    0.968110   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
111    0.968111   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
112    0.968112   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
113    0.968113   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
114    0.968114   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
115    0.968115   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
116    0.968116   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
117    0.968117   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
118    0.968118   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
119    0.968119   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
120    0.968120   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
121    0.968121   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
122    0.968122   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
123    0.968123   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
124    0.968124   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
125    0.968125   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
126    0.968126   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
127    0.968127   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
128    0.968128   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
129    0.968129   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
130    0.968130   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
131    0.968131   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
132    0.968132   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
133    0.968133   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
134    0.968134   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
135    0.968135   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
136    0.968136   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
137    0.968137   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
138    0.968138   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
139    0.968139   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
140    0.968140   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
141    0.968141   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
142    0.968142   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
143    0.968143   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
144    0.968144   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
145    0.968145   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
146    0.968146   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
147    0.968147   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
148    0.968148   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
149    0.968149   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
150    0.968150   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
151    0.968151   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
152    0.968152   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
153    0.968153   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
154    0.968154   0.344444  0.837838  0.488189  62  56554  118  12  2990.0
155    0.968155   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
156    0.968156   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
157    0.968157   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
158    0.968158   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
159    0.968159   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
160    0.968160   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
161    0.968161   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
162    0.968162   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
163    0.968163   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
164    0.968164   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
165    0.968165   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
166    0.968166   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
167    0.968167   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
168    0.968168   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
169    0.968169   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
170    0.968170   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
171    0.968171   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
172    0.968172   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
173    0.968173   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
174    0.968174   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
175    0.968175   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
176    0.968176   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
177    0.968177   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
178    0.968178   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
179    0.968179   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
180    0.968180   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
181    0.968181   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
182    0.968182   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
183    0.968183   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
184    0.968184   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
185    0.968185   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
186    0.968186   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
187    0.968187   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
188    0.968188   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
189    0.968189   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
190    0.968190   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
191    0.968191   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
192    0.968192   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
193    0.968193   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
194    0.968194   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
195    0.968195   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
196    0.968196   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
197    0.968197   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
198    0.968198   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
199    0.968199   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
200    0.968200   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
201    0.968201   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
202    0.968202   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
203    0.968203   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
204    0.968204   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
205    0.968205   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
206    0.968206   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
207    0.968207   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
208    0.968208   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
209    0.968209   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
210    0.968210   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
211    0.968211   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
212    0.968212   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
213    0.968213   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
214    0.968214   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
215    0.968215   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
216    0.968216   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
217    0.968217   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
218    0.968218   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
219    0.968219   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
220    0.968220   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
221    0.968221   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
222    0.968222   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
223    0.968223   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
224    0.968224   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
225    0.968225   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
226    0.968226   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
227    0.968227   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
228    0.968228   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
229    0.968229   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
230    0.968230   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
231    0.968231   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
232    0.968232   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
233    0.968233   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
234    0.968234   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
235    0.968235   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
236    0.968236   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
237    0.968237   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
238    0.968238   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
239    0.968239   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
240    0.968240   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
241    0.968241   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
242    0.968242   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
243    0.968243   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
244    0.968244   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
245    0.968245   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
246    0.968246   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
247    0.968247   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
248    0.968248   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
249    0.968249   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
250    0.968250   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
251    0.968251   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
252    0.968252   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
253    0.968253   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
254    0.968254   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
255    0.968255   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
256    0.968256   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
257    0.968257   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
258    0.968258   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
259    0.968259   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
260    0.968260   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
261    0.968261   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
262    0.968262   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
263    0.968263   0.346369  0.837838  0.490119  62  56555  117  12  2985.0
264    0.968264   0.346369  0.837838  0.490119  62  56555  117  12  2985.0